### ISSUE TITLE
An important logical issue

### ISSUE THREAD

**Issue by fatemi** [kuz/DeepMind-Atari-Deep-Q-Learner#22]
In the DQN loss, the update should only happen for the observed action. Assume a mini-batch of `(s, a, r, s2)` with `m` samples in the mini-batch (therefore, `s` and `s2` would be `m x n` if `n` is the nb of features and so on). Then, for sample `j` in the mini-batch, only `a[j]` should contribute to the loss, which says that all the output elements of the Q-network corresponding to the `target[j][:]` except `target[j][a[j]]` should be masked. 

Here, the target values (except `target[j][a[j]]`) are set to zero instead of masking network's output, which means the target value of zero is used and the Q-network is trained toward value `zero` for all other actions than `a[j]`, when we are at the state `s[j, :]`. 

Am I missing something?

EDIT:

It is OK (though a bit confusing). The difference has actually been put in the target and not the target itself.

**Comment by mthrok** [comment]
@fatemi 
Can you point the code you are talking about?
To me, it looks like [the code here](https://github.com/kuz/DeepMind-Atari-Deep-Q-Learner/blob/4b9f5a79b03ea0cfc512ed1c11f1b00bc875bc57/dqn/NeuralQLearner.lua#L216-L232) does what you say.

**Comment by mthrok** [comment]
oops, actually I got your point after my comment.

**Comment by fatemi** [comment]
@mthrok yes, that is where `targets` is set to zero for other actions. I dont see if network output is masked for other actions than a[j].If not, it would be a serious issue. Any idea? @kuz
