### ISSUE TITLE
hi,when  I run ./run_gpu breakout ,problem Segmentation fault  came.

### ISSUE THREAD

**Issue by Alex-zhai** [kuz/DeepMind-Atari-Deep-Q-Learner#7]

**Comment by kuz** [comment]
What system/OS do you have?
Do you have CUDA Toolkit installed? (http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#axzz3pyQeTHRr)
Running `./install_dependecies.sh` goes smoothly (no errors)?
