### ISSUE TITLE
How long does it takes to training breakout game?

### ISSUE THREAD

**Issue by dsetiady** [kuz/DeepMind-Atari-Deep-Q-Learner#8]
I am trying to running Deep Q Learn, but when i am running about 6 hours it doest seem to get smarter. I wonder how long you run the AI until its get experts to play breakout game?

**Comment by kuz** [comment]
Are you running on CPU or GPU?
It took about 30 hours on NVIDIA GTX 970 to get to the level of performance you can see on the repository main page. On CPU it should be considerably slower, did not try to estimate by how much though.

**Comment by dsetiady** [comment]
Yes, you are right. But i am just wondering because someone post that he training the AI with just 2 hours to get AI expert to playing breakout game. Its contrast with the paper that mention it took 30 minutes to reach just 1 epoch.

Btw i am using NVIDIA GTX 950.
